apiVersion: apps/v1
kind: Deployment
metadata:
  name: hybrid-server-deployment
  labels:
    app: hybrid-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hybrid-server
  template:
    metadata:
      labels:
        app: hybrid-server
    spec:
      containers:
      - name: hybrid-server
        image: dunja/pspcip/hybrid-server
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8082
          name: proxy-protocol
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
---
apiVersion: v1
kind: Service
metadata:
  name: hybrid-server
spec:
  selector:
    app: hybrid-server
  ports:
    - port: 8080
      name: http
    - port: 8082
      name: proxy-protocol