apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-with-snort-deployment
  labels:
    app: server-with-snort
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-with-snort
  template:
    metadata:
      labels:
        app: server-with-snort
    spec:
      containers:
      - name: server-with-snort
        image: miroljub1995/pspcip_server-with-snort
        imagePullPolicy: Always
        ports:
        - containerPort: 8084
          name: web
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
---
apiVersion: v1
kind: Service
metadata:
  name: server-with-snort-svc
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: server-with-snort
  ports:
    - port: 8084
      name: web